### ISSUE TITLE
Support for GitOps working group

### ISSUE THREAD

**Issue by AloisReitbauer** [fluxcd/community#39] opened 2020-11-18 20:00 UTC
Hello there,

please indicate your support for a working group on GitOps within SIG App Delivery. Please comment if you are willing to join

https://github.com/cncf/sig-app-delivery/issues/27

**Comment by stefanprodan** [comment] 2020-11-19 09:44
As a member of @fluxcd/oversight-committee I support this initiative 💯 

cc @squaremo @hiddeco

**Comment by monadic** [comment] 2020-11-19 09:49
@squaremo @stefanprodan @hiddeco please could we create a repo under the CNCF FluxCD organisation, to hold the initial documents created by this WG.  The reason is that the founders of this WG wish to manage these docs as an open source project, using the FluxCD governance.md.  As soon as this repo is created, that project work can start, and we can open an issue with CNCF to migrate the project into CNCF Sandbox, with its own org.  The project would inherit the FluxCD open governance.md doc.

**Comment by squaremo** [comment] 2020-11-19 10:08
Sorry, what is being asked here, to support the idea of a GitOps Working Group -- sure :+1: -- or to create a repository?

**Comment by stefanprodan** [comment] 2020-11-19 10:10
I think we can repurpose this issue for the repo ask, as this issue is a duplicate of https://github.com/fluxcd/community/issues/38

**Comment by stefanprodan** [comment] 2020-11-19 10:11
I propose we name the repository "gitops-manifesto".

**Comment by squaremo** [comment] 2020-11-19 10:15
This really should be a discussion rather than an issue.

**Comment by monadic** [comment] 2020-11-19 12:02
hi, happy to help with these.  first off, gitops-manifesto is ok, or could be https://github.com/fluxcd/gitops-working-group-project

**Comment by monadic** [comment] 2020-11-19 12:06
in terms of charter and purpose of group, plus who is supporting it, see 

https://github.com/cncf/sig-app-delivery/issues/27

links to draft charter 

https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit

and draft definition

https://docs.google.com/document/d/1ZgdtI8ck3DWIig5gBnbS20A0cgzBRlOT3Yv-s1b2c54/edit?ts=5fb04318

note that as I write this codefresh are + 1 and some others should appear today in the issue or the charter 

please LMK what else is needed @squaremo

**Comment by AloisReitbauer** [comment] 2020-11-19 12:27
I can also create a folder in the app delivery repo. It might fit better there

**Comment by monadic** [comment] 2020-11-19 12:31
that could be good, provided we can use fluxcd's governance.md as agreed by the initiators of this effort

**Comment by AloisReitbauer** [comment] 2020-11-19 15:57
We can use the model. I let you go ahead and create the docs. Let us figure out the details of where to put things as we go.

**Comment by monadic** [comment] 2020-11-19 17:32
moved this to Discussion: https://github.com/fluxcd/flux2/discussions/480

**Comment by dholbach** [comment] 2020-11-20 11:39
As https://github.com/fluxcd/flux2/discussions/480 is resolved, I guess we can close this?

**Closed by dholbach** 2020-11-20 11:39 UTC
